#!/bin/bash
# It requires ROOT by CERN.

#root -l 'make_map3.C("Datos_eficiencia/No_compensated.csv", "No_compensated.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Nocompensation_top.csv", "No_compensatedtop.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Nocompensation_bottom.csv", "No_compensatedbottom.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Nocompensation_walls.csv", "No_compensatedwalls.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso1m.csv", "1m.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2m.csv", "2m.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2.35.csv", "2_35.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2.35_version2.csv", "2_35_v2.pdf")' -b -q
root -l 'make_map3.C("Datos_eficiencia/Caso2_4.csv", "2_4.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2_4_version2.csv", "2_4_v2.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2m_version2.csv", "2m_v2.pdf")' -b -q
root -l 'make_map3.C("Datos_eficiencia/Caso2m_v3.csv", "2m_v3.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2_4.csv", "2.4m.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2mell.csv", "2mell.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso1m-2m.csv", "1m-2m.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso2m-1m.csv", "2m-1m.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso3m.csv", "3m.pdf")' -b -q
#root -l 'make_map3.C("Datos_eficiencia/Caso4m.csv", "4m.pdf")' -b -q

#root -l 'make_map2.C("Datos_eficiencia/FallosetA.csv", "A.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetB.csv", "B.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetC.csv", "C.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetD.csv", "D.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetE.csv", "E.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetF.csv", "F.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetG.csv", "G.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetH.csv", "H.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetI.csv", "I.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetJ.csv", "J.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetK.csv", "K.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetL.csv", "L.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetM.csv", "M.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetN.csv", "N.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetO.csv", "O.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetP.csv", "P.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetQ.csv", "Q.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetR.csv", "R.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetS.csv", "S.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetT.csv", "T.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetU.csv", "U.pdf")' -b -q
#root -l 'make_map2.C("Datos_eficiencia/FallosetV.csv", "V.pdf")' -b -q
